# -*- mode: Python -*-

local_resource(
    'deploy',
    'date +%s%N > start-time.txt',
)

docker_build('example-python-image', '.')
k8s_yaml('kubernetes.yaml')
k8s_resource('example-python', port_forwards=5000, resource_deps=['deploy'])
